### PR TITLE
Update Template and add translation pt_pt

### PR DESCRIPTION
**Pull request by jonnyforestGIS**
Hi guys, this is PR is a first attempt to update the template brochure with new logos OSGeo and QGIS and add pt_pt translation.

### CODE REVIEW

**Comment by anitagraser** [comment]
Thank you for taking the time to revisit the QGIS brochures, Goao! These brochures have certainly gathered some dust.

I realize that the newer one-page brochures that we created in 2017 based on the official OSGeo templates have not been added to this repository yet:

https://drive.google.com/file/d/0Bwc-5JFVTnfIZlloS0t4QU9raHc/view?usp=sharing

I think that it would be advantageous to use these new brochures instead of continuing with the old one since they feature new and updated texts. Furthermore, the color scheme of the old brochures unfortunately clashes with the new logo colors.

**Comment by jonnyforestGIS** [comment]
Hi @anitagraser. Do you have a vector format or project to do the changes for pt_pt based on this new layout?

**Comment by anitagraser** [comment]
Yes, I just uploaded all the material. The English version is currently only prepared in letter format: 
https://github.com/qgis/QGIS-Promotion/tree/master/brochure/en_english
but the German one also has an A4 version: 
https://github.com/qgis/QGIS-Promotion/tree/master/brochure/de_german

**Comment by jonnyforestGIS** [comment]
@anitagraser sorry for the delay on this. But I did the update with the material that you send.

**Comment by anitagraser** [comment]
Thank you, Goao!

**Pull request merged**
