### PR TITLE
add LICENSE-CC-BY-SA-4.0

### PR DESCRIPTION
**Pull request by mbernasocchi**
@anitagraser @raymondnijssen @SrNetoChan @dassau @mach0 @jonnyforestGIS @haubourg are you ok with this (since you did at least one commit to the repo)?

### CODE REVIEW

**Comment by mbernasocchi** [comment]
before merging we need all above to agree

**Comment by raymondnijssen** [comment]
+1

**Review by raymondnijssen — APPROVED** [review]

**Review by mach0 — APPROVED** [review]

**Comment by SrNetoChan** [comment]
+1

**Review by SrNetoChan — APPROVED** [review]

**Comment by jonnyforestGIS** [comment]
+1

**Comment by kannes** [comment]
Ping @anitagraser @dassau ;)

Would be great to have this under an open license.

**Review by anitagraser — APPROVED** [review]

**Comment by mbernasocchi** [comment]
ping @dassau? I'd like to merge this. what do you think?

**Review by dassau — APPROVED** [review]

**Comment by haubourg** [comment]
+1 of course

**Pull request merged**
